import { Suspense } from "react";
import { createClient } from "@/lib/supabase/server";
import { getSessionProfile } from "@/lib/auth/profile";
import { redirect } from "next/navigation";
import ChatInterface from "./ui/chat-interface";
import type { ConversationRow } from "@/types/database";

export default async function MessagesPage() {
  const { profile } = await getSessionProfile();

  if (!profile) {
    redirect("/login");
  }

  const supabase = await createClient();

  // 1. Fetch all conversation IDs the user is a part of
  const { data: myParticipants } = await supabase
    .from("conversation_participants")
    .select("conversation_id")
    .eq("user_id", profile.id);

  const convIds = myParticipants?.map(p => p.conversation_id) || [];

  if (convIds.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center p-12 mt-12 apple-card animate-in fade-in slide-in-from-bottom-4">
         <h2 className="text-xl font-bold mb-2">No Conversations Found</h2>
         <p className="text-zinc-500 max-w-md text-center">
           You are not a participant in any active class groups or direct messages.
         </p>
      </div>
    );
  }

  // 2. Fetch the actual conversations
  const { data: rawConvs } = await supabase
    .from("conversations")
    .select("*, classes(name, section)")
    .in("id", convIds)
    .order("created_at", { ascending: false });

  const rawConversations = rawConvs || [];

  // If there are direct messages, we'd need to resolve the "other" user's name.
  // For V1, we mostly have "class" type generated by triggers.
  // Let's resolve participant counts or names.
  // Fetch profiles for users in these conversations (to show sender names in chat)
  const { data: profilesInConvs } = await supabase
    .from("conversation_participants")
    .select("user_id, profiles(id, full_name, email)")
    .in("conversation_id", convIds);

  const profilesMap: Record<string, any> = {};
  if (profilesInConvs) {
     profilesInConvs.forEach(p => {
        if (p.profiles && !Array.isArray(p.profiles)) {
           profilesMap[p.user_id] = p.profiles;
        }
     });
  }

  // Augment conversations for UI
  const augmentedConversations = rawConversations.map(c => {
     let displayName = "Unknown Chat";
     if (c.type === 'class') {
       // Since it's a 1-to-1 join up from conversation -> class
       const classInfo = Array.isArray(c.classes) ? c.classes[0] : c.classes;
       displayName = classInfo ? `${classInfo.name} ${classInfo.section}` : "Class Group";
     } else {
       displayName = "Direct Message";
     }
     
     return {
       ...c,
       display_name: displayName
     };
  });

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
      <Suspense fallback={<div className="h-96 flex items-center justify-center">Loading secure connection...</div>}>
         <ChatInterface 
           userId={profile.id}
           initialConversations={augmentedConversations}
           profilesMap={profilesMap}
         />
      </Suspense>
    </div>
  );
}
