"use client";

import { useState, useEffect } from "react";
import { createClient } from "@/lib/supabase/client";
import { Zap, Mail, ArrowRight, ShieldAlert } from "lucide-react";
import type { AutomationRuleRow, EmailTemplateRow } from "@/types/database";

// Fallback toggle component if shadcn Switch is missing
function SimpleToggle({ checked, onCheckedChange }: { checked: boolean, onCheckedChange: (c: boolean) => void }) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      onClick={() => onCheckedChange(!checked)}
      className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-950 focus-visible:ring-offset-2 ${
        checked ? 'bg-[#1d1d1f]' : 'bg-zinc-200 dark:bg-zinc-800'
      }`}
    >
      <span
        className={`pointer-events-none block h-5 w-5 rounded-full bg-white shadow-lg ring-0 transition-transform ${
          checked ? 'translate-x-5' : 'translate-x-0'
        }`}
      />
    </button>
  );
}

export default function AutomationEngineView() {
  const [rules, setRules] = useState<(AutomationRuleRow & { email_templates: { name: string, subject: string } })[]>([]);
  const [loading, setLoading] = useState(true);
  
  const supabase = createClient();

  useEffect(() => {
    fetchRules();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function fetchRules() {
    const { data } = await supabase.from("automation_rules").select("*, email_templates(name, subject)").order("trigger_event", { ascending: true });
    if (data) setRules(data);
    setLoading(false);
  };

  const toggleRule = async (id: string, currentVal: boolean) => {
    const newVal = !currentVal;
    // Optimistic Update
    setRules(prev => prev.map(r => r.id === id ? { ...r, is_active: newVal } : r));
    
    const { error } = await supabase.from("automation_rules").update({ is_active: newVal }).eq("id", id);
    if (error) {
       console.error("Failed to commit rule override:", error);
       setRules(prev => prev.map(r => r.id === id ? { ...r, is_active: currentVal } : r));
    }
  };

  if (loading) return <div className="p-12 text-center text-zinc-500">Evaluating Execution Maps...</div>;

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-4xl">
      <div>
        <h1 className="text-2xl font-bold bg-gradient-to-r from-zinc-900 to-zinc-500 dark:from-zinc-100 dark:to-zinc-500 bg-clip-text text-transparent">
          Automation Engine Payload
        </h1>
        <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
          Govern implicit application triggers mapping events over to structural communication algorithms natively.
        </p>
      </div>

      <div className="bg-zinc-100 dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800/80 p-4 rounded-xl flex items-start gap-3 text-sm text-zinc-600 dark:text-zinc-400">
         <ShieldAlert className="w-5 h-5 shrink-0 mt-0.5 text-zinc-400" />
         <p>Deactivating these paths forcefully suspends implicit email and app notifications globally generated by system changes. Template configurations must be modified strictly within the specific Templates vector before attempting overrides here.</p>
      </div>

      <div className="grid gap-4">
         {rules.length === 0 ? (
            <div className="p-8 text-center text-zinc-400">No automation bounds located within framework.</div>
         ) : (
            rules.map(rule => (
                <div key={rule.id} className="apple-card flex flex-col sm:flex-row justify-between sm:items-center gap-6">
                   <div className="flex items-start sm:items-center gap-4 flex-1">
                      <div className={`mt-0.5 sm:mt-0 w-12 h-12 rounded-2xl flex items-center justify-center shrink-0 shadow-sm ${rule.is_active ? 'bg-gradient-to-br from-emerald-400 to-teal-500 text-white' : 'bg-zinc-100 text-zinc-400 dark:bg-zinc-800'}`}>
                         <Zap className="w-6 h-6" />
                      </div>
                      
                      <div className="flex-1">
                         <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 font-mono text-sm">
                            <span className="font-semibold text-zinc-900 dark:text-zinc-100 break-all">{rule.trigger_event}</span>
                            <ArrowRight className="w-4 h-4 text-zinc-300 dark:text-zinc-700 hidden sm:block shrink-0" />
                            <div className="flex items-center gap-1.5 text-zinc-500 dark:text-zinc-400 bg-zinc-50 dark:bg-zinc-900/50 px-2 py-1 rounded">
                               {rule.action_type === 'email' ? <Mail className="w-3.5 h-3.5" /> : <Zap className="w-3.5 h-3.5" />}
                               <span>Action Route: {rule.email_templates?.name || 'Unknown Template'}</span>
                            </div>
                         </div>
                         <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-2 line-clamp-1">
                            Dispatches payload structure: <span className="italic">&quot;{rule.email_templates?.subject}&quot;</span>
                         </p>
                      </div>
                   </div>
                   
                   <div className="shrink-0 flex items-center justify-end border-t sm:border-0 border-zinc-100 dark:border-zinc-800 pt-4 sm:pt-0">
                      <div className="flex items-center gap-3">
                         <span className={`text-xs font-semibold ${rule.is_active ? 'text-emerald-600 dark:text-emerald-400' : 'text-zinc-400'}`}>
                            {rule.is_active ? 'EVALUATING' : 'SUSPENDED'}
                         </span>
                         <SimpleToggle checked={rule.is_active} onCheckedChange={() => toggleRule(rule.id, rule.is_active)} />
                      </div>
                   </div>
                </div>
            ))
         )}
      </div>
    </div>
  );
}
